import RespostaModel from "../../model/resposta";
import QuestaoModel from "../../model/questao";

const questoes: QuestaoModel[] = [
    new QuestaoModel(1, "Qual destes não é filho de Adão e Eva?", [
        RespostaModel.errada('Caim'),
        RespostaModel.errada('Abel'),
        RespostaModel.errada('Sete'),
        RespostaModel.certa('Javé'),
    ]),
    new QuestaoModel(2, "Como é o nome do gigante derrotado por Davi?", [
        RespostaModel.errada('Sansão'),
        RespostaModel.errada('Zaqueu'),
        RespostaModel.errada('Salomão'),
        RespostaModel.certa('Golias'),
    ]),
    new QuestaoModel(3, "Qual destes não entrou na fornalha?", [
        RespostaModel.errada('Sadraque'),
        RespostaModel.errada('Mesaque'),
        RespostaModel.errada('Abede-nego'),
        RespostaModel.certa('Josué'),
    ]),
    new QuestaoModel(4, "Qual o nome do filho de Abraão e Sarah?", [
        RespostaModel.errada('Esmael'),
        RespostaModel.errada('Israel'),
        RespostaModel.errada('Jacó'),
        RespostaModel.certa('Isaque'),
    ]),
    new QuestaoModel(5, "Quantos anos o povo de Moisés andou pelo deserto?", [
        RespostaModel.errada('7 Anos'),
        RespostaModel.errada('27 Anos'),
        RespostaModel.errada('30 Anos'),
        RespostaModel.certa('40 Anos'),
    ]),      
    new QuestaoModel(6, "Jonas foi enviado para qual cidade?", [
        RespostaModel.errada("Nindávua"),
        RespostaModel.errada("Névua"), 
        RespostaModel.errada("Nivem"), 
        RespostaModel.certa("Ninive"),
      ]),
      new QuestaoModel(7, "Quem matou o gigante Golias?", [
        RespostaModel.errada("Daniel"), 
        RespostaModel.errada("Josué"), 
        RespostaModel.errada("Saul"), 
        RespostaModel.certa("Davi"),
      ]),
      new QuestaoModel(8, "Qual o nome do discípulo que traiu Jesus?", [
        RespostaModel.errada("Pedro"), 
        RespostaModel.errada("João"),
        RespostaModel.errada("Tiago"),
        RespostaModel.certa("Judas"),
      ]),
      new QuestaoModel(9, "Sansão era inimigo de qual povo?", [
        RespostaModel.errada("Galileus"), 
        RespostaModel.errada("Saduseus"), 
        RespostaModel.errada("Gabuzeus"), 
        RespostaModel.certa("Filisteus"), 
      ]),
      new QuestaoModel(10, "Que discipulo negou a Jesus, por 3 vezes?", [
        RespostaModel.errada("Judas"),
        RespostaModel.errada("Tiago"),
        RespostaModel.errada("João"),
        RespostaModel.certa("Pedro"), 
      ]),
      new QuestaoModel(11, "Qual profeta foi preso na ilha de Patmus?", [
            RespostaModel.errada("Gedeon"),
            RespostaModel.errada("Paulo"), 
            RespostaModel.errada("Silas"),
            RespostaModel.certa("João"), 
      ]),
      new QuestaoModel(12, "Quem batizou Jesus?", [
        RespostaModel.errada("Batista"),
        RespostaModel.errada("Espírito Santo"),
        RespostaModel.errada("Deus"), 
        RespostaModel.certa("João Batista"), 
      ]),
      new QuestaoModel(13, "Quem foi escravo e se tornou governador do Egito?", [
          RespostaModel.errada("João"), 
          RespostaModel.errada("Josué"),
          RespostaModel.errada("Kaleb"), 
          RespostaModel.certa("José"),  
      ]),
      new QuestaoModel(14, "Que animal anunciou o fim do dilúvio?", [
          RespostaModel.errada("Corvo"),
          RespostaModel.errada("Coruja"),      
          RespostaModel.errada("Urubu"),      
          RespostaModel.certa("Pomba"),      
      ]),
      new QuestaoModel(15, "Quem mergulhou sete vezes no rio jordão para ser curado de lepra?", [
        RespostaModel.errada("Noé"),      
        RespostaModel.errada("Nemias"),      
        RespostaModel.errada("Nicodemos"),      
        RespostaModel.certa("Namã"),      
      ]),
      new QuestaoModel(16, "Qual destas não foi mulher de Abraão?", [
        RespostaModel.errada("Sarah"),      
        RespostaModel.errada("Quetura"),      
        RespostaModel.errada("Agar"),      
        RespostaModel.certa("Zinrã"),      
      ]),
      new QuestaoModel(17, "Quantas pragas atormentaram o Egito?", [
        RespostaModel.errada("7"),      
        RespostaModel.errada("5"),      
        RespostaModel.errada("3"),      
        RespostaModel.certa("10"),      
      ]),
      new QuestaoModel(18, "Qual era a profissão de Jesus?", [
        RespostaModel.errada("Pastor"),      
        RespostaModel.errada("Cobrador de Impostos"),      
        RespostaModel.errada("Pescador"),      
        RespostaModel.certa("Carpinteiro"),      
      ]),
      new QuestaoModel(19, "Qual era a profissão de Jesus?", [
        RespostaModel.errada("Pastor"),      
        RespostaModel.errada("Cobrador de Impostos"),      
        RespostaModel.errada("Pescador"),      
        RespostaModel.certa("Carpinteiro"),      
      ]),
      new QuestaoModel(20, "Qual o nome do rei que criou a fornalha?", [
        RespostaModel.errada("Herodes"),      
        RespostaModel.errada("Salomão"),      
        RespostaModel.errada("Sodoma e Gomorra"),      
        RespostaModel.certa("Nabucodonossor"),      
      ]),
      new QuestaoModel(21, "Que objeto o povo criou para adorar, quando Moisés subiu o monte sinai?", [      
        RespostaModel.errada("Vaca de Ouro"),      
        RespostaModel.errada("Cabra de Ouro"),      
        RespostaModel.errada("Bezerro de Ouro"),      
        RespostaModel.certa("Touro de Ouro"),      
      ]),
      new QuestaoModel(22, "Onde Paulo pregou seu primeiro sermão?", [
        RespostaModel.errada("Beréia"),      
        RespostaModel.errada("Antioquia"),      
        RespostaModel.errada("Éfeso"),      
        RespostaModel.certa("Damasco"),      
      ]),
      new QuestaoModel(23, "Quantas pessoas entraram na Arca de Noé ?", [
          RespostaModel.errada("5"),      
          RespostaModel.errada("6"),      
          RespostaModel.errada("9"),      
          RespostaModel.certa("8"),      
      ]),
      new QuestaoModel(25, "Mais de 40 homens fizeram um voto de não comer até que houvessem cometido um homicídio, quando isso ocorreu?", [
        RespostaModel.errada("Quando queriam matar Jesus"),      
        RespostaModel.errada("Nunca aconteceu isso!"),      
        RespostaModel.errada("Quando queriam matar Estevão"),      
        RespostaModel.certa("Quando queriam matar Paulo"),      
      ]),
      new QuestaoModel(26, "Qual o capítulo da Bíblia que fala sobre o dilúvio?", [
        RespostaModel.errada("Gênesis 9"),      
        RespostaModel.errada("Êxodo 3"),      
        RespostaModel.errada("Mateus 5"),      
        RespostaModel.certa("Gênesis 7"),      
      ]),
      new QuestaoModel(27, "Quem foi vendido por 20 moedas de prata?", [
        RespostaModel.errada("Judas"),      
        RespostaModel.errada("Jesus"),      
        RespostaModel.errada("Pedro"),      
        RespostaModel.certa("José"),      
      ]),
      new QuestaoModel(28, "Faraó comprou José para que este lhe...", [
        RespostaModel.errada("Adorasse"),      
        RespostaModel.errada("Aconselhasse"),      
        RespostaModel.errada("Alegrasse"),      
        RespostaModel.certa("Interpretasse o sonho"),      
      ]),
      new QuestaoModel(29, "Quem foi o companheiro de Paulo na prisão quando se deu um grande terremoto?", [
        RespostaModel.errada("Barnabé"),      
        RespostaModel.errada("Demas"),      
        RespostaModel.errada("Tiago"),      
        RespostaModel.certa("Silas"),      
      ]),
      new QuestaoModel(30, "Como Deus chamou a porção seca no ato da criação?", [
        RespostaModel.errada("Mares"),      
        RespostaModel.errada("Montes"),      
        RespostaModel.errada("Lumináres"),      
        RespostaModel.certa("Terra"),      
      ]),
      new QuestaoModel(31, "Quem colocou fogo na seara dos filisteus com 300 raposas?", [
        RespostaModel.errada("Otoniel"),      
        RespostaModel.errada("Jefté"),      
        RespostaModel.errada("Gideão"),      
        RespostaModel.certa("Sansão"),      
      ]),
      new QuestaoModel(32, "Sara a mulher de Abraão, morreu em...", [
        RespostaModel.errada("Jerusalém"),     
        RespostaModel.errada("Jericó"),      
        RespostaModel.errada("Nazaré"),      
        RespostaModel.certa("Hebrom (Quiriate-Arba)"),      
      ]),
      new QuestaoModel(33, "Com que idade morreu Sara mulher de Abraão?", [
        RespostaModel.errada("120"),      
        RespostaModel.errada("130"),      
        RespostaModel.errada("140"),      
        RespostaModel.certa("127"),      
      ]),
      new QuestaoModel(34, "Além de mulher de Abraão, Sará também era sua...", [
        RespostaModel.errada("Prima"),      
        RespostaModel.errada("Irmã por parte de sua mãe"),      
        RespostaModel.errada("Irmã de Ló"),      
        RespostaModel.certa("Irmã por parte de seu pai"),      
      ]),
      new QuestaoModel(35, "Com que idade Sara teve o filho Isaque?", [
        RespostaModel.errada("85 Anos"),      
        RespostaModel.errada("95 Anos"),      
        RespostaModel.errada("100 Anos"),      
        RespostaModel.certa("90 Anos"),      
      ]),
      new QuestaoModel(37, "Qual foi o rei que abriu uma janela por ordem de um profeta?", [
        RespostaModel.errada("Jeremias"),      
        RespostaModel.errada("Elias"),      
        RespostaModel.errada("Isaías"),      
        RespostaModel.certa("Eliseu"),      
      ]),
      new QuestaoModel(38, "Em qual livro da bíblia fala sobre uma serpente marítima?", [
        RespostaModel.errada("Jó"),      
        RespostaModel.errada("Atos"),      
        RespostaModel.errada("Gênesis"),      
        RespostaModel.certa("Amós"),      
      ]),
      new QuestaoModel(39, "Quando Jacó fugiu de Labão, quantos dias depois este ficou sabendo?", [
        RespostaModel.errada("2"),      
        RespostaModel.errada("5"),      
        RespostaModel.errada("9"),      
        RespostaModel.certa("7"),      
      ]),
      new QuestaoModel(40, "Raquel morreu próximo a que cidade?", [
        RespostaModel.errada("Jericó"),      
        RespostaModel.errada("Nazaré"),      
        RespostaModel.errada("Maanaim"),      
        RespostaModel.certa("Efrata"),      
      ]),
      new QuestaoModel(41, "Qual rei foi denominado querubim ungido?", [
        RespostaModel.errada("Zinri"),      
        RespostaModel.errada("Abias"),      
        RespostaModel.errada("Joacaz"),      
        RespostaModel.certa("Tiro"),      
      ]),
      new QuestaoModel(42, "Quem fez bolos asmos para um anjo?", [
        RespostaModel.errada("Zacarias"),      
        RespostaModel.errada("Abraão"),      
        RespostaModel.errada("Elias"),      
        RespostaModel.certa("Gideões"),      
      ]),
      new QuestaoModel(43, "Onde Isaque levantou um altar ao Senhor, após Este haver lhe aparecido?", [
        RespostaModel.errada("Preobote"),      
        RespostaModel.errada("Gerar"),      
        RespostaModel.errada("Eseque"),      
        RespostaModel.certa("Berseba"),      
      ]),
      new QuestaoModel(44, "Quais vidas foram salvas por um fio vermelho?", [
        RespostaModel.errada("Balaque e Balaão"),      
        RespostaModel.errada("Arão e Hur"),      
        RespostaModel.errada("Josue e Kalebe"),      
        RespostaModel.certa("Dois espias e Dois israelitas"),      
      ]),
      new QuestaoModel(45, "Para onde Ló foi ao sair de Sodoma?", [
        RespostaModel.errada("Cades"),      
        RespostaModel.errada("Sur"),      
        RespostaModel.errada("Gerar"),      
        RespostaModel.certa("Zoar"),      
      ]),
      new QuestaoModel(46, "Qual foi o último desejo de Jacó ?", [
        RespostaModel.errada("Nenhuma das alternativas"),      
        RespostaModel.errada("Que seus filhos fossem bem sucedidos"),      
        RespostaModel.errada("Que José fosse bom com seus irmãos"),      
        RespostaModel.certa("Que ele não fosse sepultado no Egito"),      
      ]),
      new QuestaoModel(47,  "Como se chamavam os habitantes de Siquem, quando lá chegou Abrão vindo de Harã?", [
        RespostaModel.errada("Fenícios"),      
        RespostaModel.errada("Caldeus"),      
        RespostaModel.errada("Egípsios"),      
        RespostaModel.certa("Cananeus"),      
      ]),
      new QuestaoModel(48, "Qual mulher matou um homem enfiando uma estaca no crânio?", [
        RespostaModel.errada("Débora"),      
        RespostaModel.errada("Ester"),      
        RespostaModel.errada("Jezabel"),      
        RespostaModel.certa("Jael"),      
      ]),
      new QuestaoModel(49, "Quantos braços tinha o rio que saia do Éden ?", [
        RespostaModel.errada("2"),      
        RespostaModel.errada("3"),      
        RespostaModel.errada("5"),      
        RespostaModel.certa("4"),      
      ]),
      new QuestaoModel(50, "Quantos anos tinha Jacó quando se apresentou a Faraó ?", [
        RespostaModel.errada("30"),      
        RespostaModel.errada("40"),      
        RespostaModel.errada("140"),      
        RespostaModel.certa("130"),      
      ]),
      new QuestaoModel(51, "O que Deus mandou Noé construir para colocar os animais dentro?", [
        RespostaModel.errada("Casa"),      
        RespostaModel.errada("Submarino"),      
        RespostaModel.errada("Avião"),      
        RespostaModel.certa("Arca"),     
      ]),
      new QuestaoModel(52, "Qual o nome da mulher de Adão?", [
        RespostaModel.errada("Maria"),      
        RespostaModel.errada("Serpente"),      
        RespostaModel.errada("Sara"),      
        RespostaModel.certa("Eva"),      
      ]),
      new QuestaoModel(53, "O que a serpente deu para Eva comer?", [
        RespostaModel.errada("Maça"),      
        RespostaModel.errada("Tomate"),      
        RespostaModel.errada("Cereja"),      
        RespostaModel.certa("Fruto Proibido"),      
      ]),
      new QuestaoModel(54, "Quantos ladrões tinha ao lado de Jesus?", [
        RespostaModel.errada("5"),    
        RespostaModel.errada("4"),      
        RespostaModel.errada("3"),      
        RespostaModel.certa("2"),      
      ]),
      new QuestaoModel(55, "Quantos eram os dicípulos de Jesus?", [
        RespostaModel.errada("10"),      
        RespostaModel.errada("14"),      
        RespostaModel.errada("26"),      
        RespostaModel.certa("12"),      
      ]),
      new QuestaoModel(56, "O que representa o copo de Cristo na Santa Seia?", [
        RespostaModel.errada("Queijo"),      
        RespostaModel.errada("Vinho"),      
        RespostaModel.errada("Cálice"),      
        RespostaModel.certa("Pão"),      
      ]),
      new QuestaoModel(57, "O que representa o sangue de Cristo na Santa Seia?", [
        RespostaModel.errada("Queijo"),      
        RespostaModel.errada("Cálice"),      
        RespostaModel.errada("Pão"),      
        RespostaModel.certa("Vinho"),      
      ]),
      new QuestaoModel(58, "Jonas foi engulido por que animal?", [
        RespostaModel.errada("Jacaré"),      
        RespostaModel.errada("Leão"),      
        RespostaModel.errada("Urso"),      
        RespostaModel.certa("Grande Peixe"),      
      ]),
      new QuestaoModel(59, "Onde Zaqueu subiu para ver Jesus no meio da multidão?", [
        RespostaModel.errada("Casa"),      
        RespostaModel.errada("Rocha"),      
        RespostaModel.errada("Telhado da Igreja"),      
        RespostaModel.certa("Árvore"),      
      ]),
]

export default questoes